language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=foncia)
  - secure: B6kKHh89FZKj1txvQkwIeBT28If0rsjzzLlRcGLdXfaeJ5NAjiOoyRIEi5vlZLlqCRk2A8ashkAxA3gwStadVYg9bhxQXWXZNJKJVz2Z2XfIHW6glM2ZvafdTosr7INgNX/drFInB6fG+wsYhXs3cDFG2CQYEm081/sj7bjOxIGGTVAqFd+uzVVRdYY0azXz7FcIPc2OXY3C9TfWHMnMDEXeEsIWs+mCQJmsyQLo0nLDin3hh77Z31/YGupAJpCgQBRzPIxizZ21Jmv4Ia/HUn6FA5meK/Ehk4eJNDjAFCa35M6++NyI6zVDRtKdiOjwtUkqK51UePLcCt7bAzYKeVL65l34E+efoDF/XQBI76yrfXDowKNoAq9YNOPeBRJlb31ryxdDNxkz+gfTHqNd3d/EAQF1HkzQtFdc2V5m8RI1dXlKU+61y9tSBjBdlWz97s1HNg6tdMS008/McRmm2sMeqXxcTCV+SiFVZ+eEct2Fc5uXwbtrAui7/QBl2TPBHpSdHMF8s5x9AYLUVLxJCX8Gz/2JsBkqx5DqrhK4fbggLsIyAtKFYsqxBEREzrEQKHxj2tl2eueXGbo1UI2LnzfJXVUTOujwOd7sVr0VhLIISipgurntz78hh/xZ1ZX3KgpZEBSm9+d63fgp1TxunTd76GuyR5k11tU9feHDas8=
  # MATTERMOST_HOOK_URL
  - secure: YMLtqdYabHh+vKhdcZ1E20/UQgkdW6zk6Tuj96wcnCEH3SOHAxMz55EzdGte0ZhfBzMekpFZzqIg6G2yfos4rjJ3OlBkb0alGV9cFQ/8x9fkAQiaSnO/85Qn9erogoRoq2WwcRzV0SDoWb6svCPlHs/dEWIlIn/HX9OBHw8WHpiYiSh7q0gBjR7n9IbP6bSweWNAjC+15XCqctm8XMytweTudi+ceU5ZtjZW5vD0+nJD7s2XcKWBNnCn+As9e+AALLUZABHJM107wy8J5EPEuvXl15XnLqJ1aAGmRPd72ChextKjKrK6CGemW0k8mf85cexRxcQbWqsY/DJ9Rb0FM26Bb+Vs1HGidpRfw/a8EveqtPswKFINJxLGmWMcUkQa8hqC/GBdDdkbUMrgCNx4lYjsVDmstDKD6kHqRDtn6ZFWiJeIH3PjVCx/sl/NfbH4LNqh1NVZfp4k18wlDY6Z2ttbFR/PHqw53HzizkR/FBrDfVSR+vgxDET8T4Q3HDm+UIIH80BJQpyjwlJJSxc/c3Hz8QCWlE6S7x1X9fHOxymKYm+oDV7xzn5TyM2E8UgVSRQzDYkNuQoBskmbzZMHHiyXpuC91YyJ+g52bATzdqHUB7MQAW9wrqWnvz6zOmFFKkYN9sUFxQIWo+h8X+O0/oMo2xgXb7+/zT2IY6HHwZg=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
